# Generated by Django 5.1.15 on 2026-05-28 18:15

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('business_type', models.CharField(choices=[('bakery', 'Bakery / Bäckerei'), ('butcher', 'Butcher / Metzgerei'), ('grocery', 'Grocery / Lebensmittel'), ('clothing', 'Clothing / Bekleidung'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('retail', 'Retail / Einzelhandel'), ('tour_operator', 'Tour Operator'), ('hotel', 'Hotel'), ('other', 'Other')], default='other', max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='DE', max_length=2)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('default_locale', models.CharField(default='de', max_length=10)),
                ('enabled_locales', models.JSONField(default=list)),
                ('default_currency', models.CharField(default='EUR', max_length=3)),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=50)),
                ('data_region', models.CharField(default='EU', max_length=10)),
                ('enabled_modules', models.JSONField(default=list)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('subscription_status', models.CharField(default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('owner_phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
